// countries.js

export const countries_en = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia (Czech Republic)',
    'Democratic Republic of the Congo (Congo-Kinshasa)',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini (fmr. "Swaziland")',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (formerly Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia (formerly Macedonia)',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
  
  export const countries_ru = [
    'Афганистан',
    'Албания',
    'Алжир',
    'Андорра',
    'Ангола',
    'Антигуа и Барбуда',
    'Аргентина',
    'Армения',
    'Австралия',
    'Австрия',
    'Азербайджан',
    'Багамы',
    'Бахрейн',
    'Бангладеш',
    'Барбадос',
    'Беларусь',
    'Бельгия',
    'Белиз',
    'Бенин',
    'Бутан',
    'Боливия',
    'Босния и Герцеговина',
    'Ботсвана',
    'Бразилия',
    'Бруней',
    'Болгария',
    'Буркина-Фасо',
    'Бурунди',
    'Кабо-Верде',
    'Камбоджа',
    'Камерун',
    'Канада',
    'Центральноафриканская Республика',
    'Чад',
    'Чили',
    'Китай',
    'Колумбия',
    'Коморские Острова',
    'Конго (Конго-Браззавиль)',
    'Коста-Рика',
    'Хорватия',
    'Куба',
    'Кипр',
    'Чехия (Чешская Республика)',
    'Демократическая Республика Конго (Конго-Киншаса)',
    'Дания',
    'Джибути',
    'Доминика',
    'Доминиканская Республика',
    'Восточный Тимор (Тимор-Лешти)',
    'Эквадор',
    'Египет',
    'Сальвадор',
    'Экваториальная Гвинея',
    'Эритрея',
    'Эстония',
    'Эсватини (бывш. Свазиленд)',
    'Эфиопия',
    'Фиджи',
    'Финляндия',
    'Франция',
    'Габон',
    'Гамбия',
    'Грузия',
    'Германия',
    'Гана',
    'Греция',
    'Гренада',
    'Гватемала',
    'Гвинея',
    'Гвинея-Бисау',
    'Гайана',
    'Гаити',
    'Гондурас',
    'Венгрия',
    'Исландия',
    'Индия',
    'Индонезия',
    'Иран',
    'Ирак',
    'Ирландия',
    'Израиль',
    'Италия',
    'Кот д`Ивуар',
    'Ямайка',
    'Япония',
    'Иордания',
    'Казахстан',
    'Кения',
    'Кирибати',
    'КНДР',
    'Республика Корея',
    'Косово',
    'Кувейт',
    'Кыргызстан',
    'Лаос',
    'Латвия',
    'Ливан',
    'Лесото',
    'Либерия',
    'Ливия',
    'Лихтенштейн',
    'Литва',
    'Люксембург',
    'Мадагаскар',
    'Малави',
    'Малайзия',
    'Мальдивы',
    'Мали',
    'Мальта',
    'Маршалловы Острова',
    'Мавритания',
    'Маврикий',
    'Мексика',
    'Микронезия',
    'Молдова',
    'Монако',
    'Монголия',
    'Черногория',
    'Марокко',
    'Мозамбик',
    'Мьянма (бывш. Бирма)',
    'Намибия',
    'Науру',
    'Непал',
    'Нидерланды',
    'Новая Зеландия',
    'Никарагуа',
    'Нигер',
    'Нигерия',
    'Северная Македония (бывш. Македония)',
    'Норвегия',
    'Оман',
    'Пакистан',
    'Палау',
    'Государство Палестина',
    'Панама',
    'Папуа-Новая Гвинея',
    'Парагвай',
    'Перу',
    'Филиппины',
    'Польша',
    'Португалия',
    'Катар',
    'Румыния',
    'Россия',
    'Руанда',
    'Сент-Китс и Невис',
    'Сент-Люсия',
    'Сент-Винсент и Гренадины',
    'Самоа',
    'Сан-Марино',
    'Сан-Томе и Принсипи',
    'Саудовская Аравия',
    'Сенегал',
    'Сербия',
    'Сейшельские Острова',
    'Сьерра-Леоне',
    'Сингапур',
    'Словакия',
    'Словения',
    'Соломоновы Острова',
    'Сомали',
    'Южно-Африканская Республика',
    'Южный Судан',
    'Испания',
    'Шри-Ланка',
    'Судан',
    'Суринам',
    'Швеция',
    'Швейцария',
    'Сирия',
    'Тайвань',
    'Таджикистан',
    'Танзания',
    'Таиланд',
    'Того',
    'Тонга',
    'Тринидад и Тобаго',
    'Тунис',
    'Турция',
    'Туркменистан',
    'Тувалу',
    'Уганда',
    'Украина',
    'Объединенные Арабские Эмираты',
    'Великобритания',
    'Соединенные Штаты Америки',
    'Уругвай',
    'Узбекистан',
    'Вануату',
    'Ватикан',
    'Венесуэла',
    'Вьетнам',
    'Йемен',
    'Замбия',
    'Зимбабве',
  ];
