

export const defaultFormValues = {
    email: '',
    contactName: '',
    contactPreference: '',
    contactPosition: '',
    region: '',
    country: '',
    municipality: '',
    orgName: '',
    orgType: '',
    ongoingProgram: '',
    soilTopics: '',
    implementationScale: '',
    involveInstitutions: '',
    targetCommunitySize: '',
    developedMaterials: '',
    accessToFunds: '',
    agreementWithToR: '',
    feedback: '',
    stage: 'Awaiting Reply',
    replyDate: null,
    replyContent: null,
    actorType: null,
    mapInstitutionName: null,
    registeredInMap: false,
    registeredInMapDesc: "",
    comments: null,
};
